CREATE DATABASE IF NOT EXISTS `918ch` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE 918ch;

CREATE TABLE IF NOT EXISTS `posts`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`body` VARCHAR(255) NOT NULL,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
